// <auto-generated />
using System;
using LeadPipe.Infrastructure.Sqlite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadPipe.Infrastructure.Sqlite.Migrations
{
    [DbContext(typeof(PlumbingContext))]
    [Migration("20251225233900_AddUniqueIndexToCallEntities")]
    partial class AddUniqueIndexToCallEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Billable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixCallDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("PhoneNumber", "CallDate")
                        .IsUnique();

                    b.ToTable("CallEntities");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CallSubsLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CallId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.HasIndex("SubsId");

                    b.HasIndex("SubsId", "CallId")
                        .IsUnique();

                    b.ToTable("SubsCallLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingCallLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CallId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.HasIndex("PlumbingId");

                    b.HasIndex("PlumbingId", "CallId")
                        .IsUnique();

                    b.ToTable("PlumbingCallLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("PhoneNumber", "Source")
                        .IsUnique();

                    b.ToTable("PlumbingEntities");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SubsEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Number2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SubActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubCancelDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixCancelDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixSubCancelDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixSubDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("Number2");

                    b.ToTable("SubsEntities");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SubsPlumbingLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingSubPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlumbingId");

                    b.HasIndex("SubsId");

                    b.HasIndex("SubsId", "PlumbingId")
                        .IsUnique();

                    b.ToTable("SubsPlumbingLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SyncStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastProcessedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixLastSyncUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SyncState");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CallSubsLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CallEntity", "CallEntity")
                        .WithMany("SubsCallLinks")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.SubsEntity", "SubsEntity")
                        .WithMany("SubsCallLinks")
                        .HasForeignKey("SubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallEntity");

                    b.Navigation("SubsEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingCallLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CallEntity", "CallEntity")
                        .WithMany("PlumbingCallLinks")
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "PlumbingEntity")
                        .WithMany("PlumbingCallLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CallEntity");

                    b.Navigation("PlumbingEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SubsPlumbingLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "PlumbingEntity")
                        .WithMany("SubsPlumbingLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.SubsEntity", "SubsEntity")
                        .WithMany("SubsPlumbingLinks")
                        .HasForeignKey("SubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlumbingEntity");

                    b.Navigation("SubsEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CallEntity", b =>
                {
                    b.Navigation("PlumbingCallLinks");

                    b.Navigation("SubsCallLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", b =>
                {
                    b.Navigation("PlumbingCallLinks");

                    b.Navigation("SubsPlumbingLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SubsEntity", b =>
                {
                    b.Navigation("SubsCallLinks");

                    b.Navigation("SubsPlumbingLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
