// <auto-generated />
using System;
using LeadPipe.Infrastructure.Sqlite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeadPipe.Infrastructure.Sqlite.Migrations
{
    [DbContext(typeof(PlumbingContext))]
    [Migration("20260325175605_AddLabelColumnToCaliperEntities")]
    partial class AddLabelColumnToCaliperEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Billable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("CaliperEntities", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornCaliperLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CaliperId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CornId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaliperId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("CornId", "CaliperId")
                        .IsUnique();

                    b.ToTable("CornCaliperLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CornCaliper_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber", "Source");

                    b.ToTable("CornEntities", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornPlumbingLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CornId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlumbingId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("CornId", "PlumbingId")
                        .IsUnique();

                    b.ToTable("CornPlumbingLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CornPlumbing_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardCaliperLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CaliperId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustardId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaliperId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("CustardId", "CaliperId")
                        .IsUnique();

                    b.ToTable("CustardCaliperLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustardCaliper_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardCornLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CornId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustardId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CornId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("CustardId", "CornId")
                        .IsUnique();

                    b.ToTable("CustardCornLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustardCorn_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PhoneNumber2")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixCancelDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("PhoneNumber2");

                    b.ToTable("CustardEntities", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardPlumbingLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustardId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlumbingId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("CustardId", "PlumbingId")
                        .IsUnique();

                    b.ToTable("CustardPlumbingLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_CustardPlumbing_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingCaliperLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CaliperId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaliperId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("PlumbingId", "CaliperId")
                        .IsUnique();

                    b.ToTable("PlumbingCaliperLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlumbingCaliper_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PhoneNumber", "UnixDate", "Source", "MetaData")
                        .IsUnique();

                    b.ToTable("PlumbingEntities", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandCaliperLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CaliperId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaliperId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("SandId", "CaliperId")
                        .IsUnique();

                    b.ToTable("SandCaliperLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_SandCaliper_MatchingPhone", "MatchingPhone");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandCornLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CornId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CornId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("SandId", "CornId")
                        .IsUnique();

                    b.ToTable("SandCornLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_SandCorn_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CancelDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Complete")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustardId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Offerman")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seller")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seller3")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixCancelDate")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixDate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustardId");

                    b.ToTable("SandEntities", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandPlumbingLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MatchingPhone")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlumbingId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixMatchDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlumbingId");

                    b.HasIndex("UnixMatchDate");

                    b.HasIndex("SandId", "PlumbingId")
                        .IsUnique();

                    b.ToTable("SandPlumbingLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_SandPlumbing_MatchingPhone", "MatchingPhone <> 0");
                        });
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SyncStampEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuccessState")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnixSyncUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Source")
                        .IsUnique()
                        .HasFilter("Source IS NOT NULL");

                    b.ToTable("SyncStamp", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SyncStateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastProcessedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnixLastSyncUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("SyncState", (string)null);
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornCaliperLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", "CaliperEntity")
                        .WithMany("CornCaliperLinks")
                        .HasForeignKey("CaliperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", "CornEntity")
                        .WithMany("CornCaliperLinks")
                        .HasForeignKey("CornId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaliperEntity");

                    b.Navigation("CornEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornPlumbingLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", "CornEntity")
                        .WithMany("CornPlumbingLinks")
                        .HasForeignKey("CornId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "PlumbingEntity")
                        .WithMany("CornPlumbingLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CornEntity");

                    b.Navigation("PlumbingEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardCaliperLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", "Caliper")
                        .WithMany("CustardCaliperLinks")
                        .HasForeignKey("CaliperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", "Custard")
                        .WithMany("CustardCaliperLinks")
                        .HasForeignKey("CustardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caliper");

                    b.Navigation("Custard");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardCornLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", "Corn")
                        .WithMany("CustardCornLinks")
                        .HasForeignKey("CornId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", "Custard")
                        .WithMany("CustardCornLinks")
                        .HasForeignKey("CustardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corn");

                    b.Navigation("Custard");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardPlumbingLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", "Custard")
                        .WithMany("CustardPlumbingLinks")
                        .HasForeignKey("CustardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "Plumbing")
                        .WithMany("CustardPlumbingLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Custard");

                    b.Navigation("Plumbing");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingCaliperLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", "CaliperEntity")
                        .WithMany("PlumbingCaliperLinks")
                        .HasForeignKey("CaliperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "PlumbingEntity")
                        .WithMany("PlumbingCaliperLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaliperEntity");

                    b.Navigation("PlumbingEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandCaliperLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", "CaliperEntity")
                        .WithMany("SandCaliperLinks")
                        .HasForeignKey("CaliperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", "SandEntity")
                        .WithMany("SandCaliperLinks")
                        .HasForeignKey("SandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaliperEntity");

                    b.Navigation("SandEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandCornLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", "CornEntity")
                        .WithMany("SandCornLinks")
                        .HasForeignKey("CornId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", "SandEntity")
                        .WithMany("SandCornLinks")
                        .HasForeignKey("SandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CornEntity");

                    b.Navigation("SandEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", "CustardEntity")
                        .WithMany("SandEntities")
                        .HasForeignKey("CustardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustardEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandPlumbingLink", b =>
                {
                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", "PlumbingEntity")
                        .WithMany("SandPlumbingLinks")
                        .HasForeignKey("PlumbingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", "SandEntity")
                        .WithMany("SandPlumbingLinks")
                        .HasForeignKey("SandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlumbingEntity");

                    b.Navigation("SandEntity");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CaliperEntity", b =>
                {
                    b.Navigation("CornCaliperLinks");

                    b.Navigation("CustardCaliperLinks");

                    b.Navigation("PlumbingCaliperLinks");

                    b.Navigation("SandCaliperLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CornEntity", b =>
                {
                    b.Navigation("CornCaliperLinks");

                    b.Navigation("CornPlumbingLinks");

                    b.Navigation("CustardCornLinks");

                    b.Navigation("SandCornLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.CustardEntity", b =>
                {
                    b.Navigation("CustardCaliperLinks");

                    b.Navigation("CustardCornLinks");

                    b.Navigation("CustardPlumbingLinks");

                    b.Navigation("SandEntities");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.PlumbingEntity", b =>
                {
                    b.Navigation("CornPlumbingLinks");

                    b.Navigation("CustardPlumbingLinks");

                    b.Navigation("PlumbingCaliperLinks");

                    b.Navigation("SandPlumbingLinks");
                });

            modelBuilder.Entity("LeadPipe.Infrastructure.Entity.Sqlite.SandEntity", b =>
                {
                    b.Navigation("SandCaliperLinks");

                    b.Navigation("SandCornLinks");

                    b.Navigation("SandPlumbingLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
