namespace LeadPipe.Infrastructure.Entity.MySql;
public class CustardMySqlEntity
{
#pragma warning disable IDE1006 // Naming Styles
    public int customerID { get; set; }
    public int billToAccountID { get; set; }
    public int officeID { get; set; }
    public string? fname { get; set; }
    public string? lname { get; set; }
    public string? companyName { get; set; }
    public string? spouse { get; set; }
    public int commercialAccount { get; set; }
    public int status { get; set; }
    public string? statusText { get; set; }
    public string? email { get; set; }
    public string? phone1 { get; set; }
    public string? phone2 { get; set; }
    public string? address { get; set; }
    public string? city { get; set; }
    public string? state { get; set; }
    public string? zip { get; set; }
    public string? billingCompanyName { get; set; }
    public string? billingFName { get; set; }
    public string? billingLName { get; set; }
    public string? billingCountryID { get; set; }
    public string? billingAddress { get; set; }
    public string? billingCity { get; set; }
    public string? billingState { get; set; }
    public string? billingZip { get; set; }
    public string? billingPhone { get; set; }
    public string? billingEmail { get; set; }
    public double lat { get; set; }
    public double lng { get; set; }
    public int squareFeet { get; set; }
    public int addedByID { get; set; }
    public DateTime dateAdded { get; set; }
    public DateTime dateCancelled { get; set; }
    public DateTime dateUpdated { get; set; }
    public int sourceID { get; set; }
    public string? source { get; set; }
    public string? aPay { get; set; }
    public int preferredTechID { get; set; }
    public int paidInFull { get; set; }
    public string? subscriptionIDs { get; set; }
    public double balance { get; set; }
    public int balanceAge { get; set; }
    public double responsibleBalance { get; set; }
    public int responsibleBalanceAge { get; set; }
    public string? customerLink { get; set; }
    public int masterAccount { get; set; }
    public int preferredBillingDate { get; set; }
    public DateTime paymentHoldDate { get; set; }
    public string? mostRecentCreditCardLastFour { get; set; }
    public string? mostRecentCreditCardExpirationDate { get; set; }
    public string? appointmentIDs { get; set; }
    public string? ticketIDs { get; set; }
    public string? paymentIDs { get; set; }
    public DateTime snapshotDate { get; set; }
    public string? cancellationNotes { get; set; }
    public int cancelledBy { get; set; }
    public string? cancellationReason { get; set; }
    public int showTech { get; set; }
    public int regionID { get; set; }
    public int servsuiteAccount { get; set; }
    public string? county { get; set; }
    public double maxMonthCharge { get; set; }
    public int useStructures { get; set; }
    public int isMultiUnit { get; set; }
    public string? fullName { get; set; }
    public string? customState { get; set; }
    public double taxRate { get; set; }
    public string? customerFlagText { get; set; }
    public string? subPropertyType { get; set; }
#pragma warning restore IDE1006 // Naming Styles
}
