namespace LeadPipe.Infrastructure.Entity.MySql;
public class SubMySqlEntity
{
#pragma warning disable IDE1006 // Naming Styles
    public int subscriptionID { get; set; }
    public DateTime snapshotDate { get; set; }
    public int customerID { get; set; }
    public int billToAccountID { get; set; }
    public int officeID { get; set; }
    public DateTime dateAdded { get; set; }
    public DateTime contractAdded { get; set; }
    public int active { get; set; }
    public string? activeText { get; set; }
    public decimal initialQuote { get; set; }
    public decimal initialDiscount { get; set; }
    public decimal initialServiceTotal { get; set; }
    public decimal yifDiscount { get; set; }
    public decimal recurringCharge { get; set; }
    public decimal contractValue { get; set; }
    public string? billingFrequency { get; set; }
    public string? frequency { get; set; }
    public int followupService { get; set; }
    public int agreementLength { get; set; }
    public DateTime nextService { get; set; }
    public DateTime lastCompleted { get; set; }
    public int serviceID { get; set; }
    public string? serviceType { get; set; }
    public int soldBy { get; set; }
    public int preferredTech { get; set; }
    public int initialAppointmentID { get; set; }
    public int initialStatus { get; set; }
    public string? initialStatusText { get; set; }
    public DateTime dateCancelled { get; set; }
    public DateTime dateUpdated { get; set; }
    public string? cxlNotes { get; set; }
    public string? subscriptionLink { get; set; }
    public int sourceID { get; set; }
    public string? source { get; set; }
    public int annualRecurringServices { get; set; }
    public string? cancellationNotes { get; set; }
    public int cancelledBy { get; set; }
    public string? cancellationReason { get; set; }
    public int showTech { get; set; }
    public int cancellationReasonID { get; set; }
    public int typeID { get; set; }
    public string? type { get; set; }
    public string? noteCancellation { get; set; }
    public DateOnly dateReactived { get; set; }
    public DateOnly dateAddedDate { get; set; }
    public int regionID { get; set; }
    public int soldBy2 { get; set; }
    public int soldBy3 { get; set; }
    public DateOnly customDate { get; set; }
    public DateOnly customNextService { get; set; }
    public int sentriconSiteID { get; set; }
    public int sentriconConnected { get; set; }
    public DateOnly seasonStart { get; set; }
    public DateOnly seasonEnd { get; set; }
    public DateOnly nextBillingDate { get; set; }
    public decimal originalContractValue { get; set; }
    public DateOnly expirationDate { get; set; }
    public double balance { get; set; }
    public double addOnTotal { get; set; }
    public int flaggedQBS { get; set; }
    public int paid { get; set; }
    public decimal initialWriteOffAmount { get; set; }
    public int originalAgreementLength { get; set; }
    public DateTime originalDateAdded { get; set; }
    public string? subscriptionFlagText { get; set; }
    public int minRecurringTicketID { get; set; }
    public decimal recurringServiceCharge { get; set; }
    public string? recurringTicketItems { get; set; }
    public decimal expectedAnnualValue { get; set; }
    public int anticipatedServices { get; set; }
    public int anticipatedBillings { get; set; }
    public int commercialAccount { get; set; }
    public int billingTermsDays { get; set; }
    public string? poNumber { get; set; }
    public string? initialInvoice { get; set; }
    public DateOnly initialBillingDate { get; set; }
    public int renewalFrequency { get; set; }
    public int onHold { get; set; }
    public int customScheduleID { get; set; }
    public string? unitIDs { get; set; }
    public int parentID { get; set; }
    public decimal annualRecurringValue { get; set; }
#pragma warning restore IDE1006 // Naming Styles
}